import { useEffect } from 'react'
import { Link } from 'react-router-dom'

export default function NotFound() {
  // Client-side only -- prerender.js generates dist/404.html as static HTML.
  // This component only runs when React Router can't match a client-side navigation.
  useEffect(() => {
    document.title = 'Page Not Found | cf-seo-ssr example'
  }, [])

  return (
    <div>
      <p className="page-eyebrow">404</p>
      <h1 className="page-heading">Page not found.</h1>
      <p className="page-body">
        That route doesn't exist. The real 404 page (<code>dist/404.html</code>)
        is generated by prerender.js and served by CF Pages with a genuine HTTP 404.
      </p>
      <Link to="/" style={{ display: 'inline-block', marginTop: '1.5rem' }}>
        &larr; Back to home
      </Link>
    </div>
  )
}
